In [1]:
import torch
import torch.nn as nn
from torch_geometric.nn import GCNConv

In [2]:
x = torch.tensor([
    [1., 2.],
    [2., 3.],
    [4., 1.]
])

edge_index = torch.tensor([
    [0, 1, 0, 2, 1, 2],
    [1, 0, 2, 0, 2, 1]
], dtype=torch.long)

print("Node features:")
print(x)

print("\nEdge index:")
print(edge_index)

Node features:
tensor([[1., 2.],
        [2., 3.],
        [4., 1.]])

Edge index:
tensor([[0, 1, 0, 2, 1, 2],
        [1, 0, 2, 0, 2, 1]])


In [5]:
class GNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = GCNConv(2, 4)
        self.conv2 = GCNConv(4, 2)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = torch.relu(x)

        x = self.conv2(x, edge_index)

        return x

In [6]:
y = torch.tensor([
    [3., 3.],
    [3., 3.],
    [3., 3.]
])

print(y)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])


In [7]:
model = GNN()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.01
)

In [8]:
for epoch in range(500):

    pred = model(x, edge_index)

    loss = torch.mean((pred - y) ** 2)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 50 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.6f}")

Epoch 300, Loss: 0.011476
Epoch 350, Loss: 0.000320
Epoch 400, Loss: 0.000002
Epoch 450, Loss: 0.000000


In [9]:
with torch.no_grad():
    pred = model(x, edge_index)

print("Prediction:")
print(pred)

print("\nTarget:")
print(y)

Prediction:
tensor([[3.0000, 3.0000],
        [3.0000, 3.0000],
        [3.0000, 3.0000]])

Target:
tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])
