In [1]:
import numpy as np

image = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0],
    [0, 1, 1, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])

kernel = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

print("Image:")
print(image)

print("\nKernel:")
print(kernel)

Image:
[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Kernel:
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


In [3]:
region = image[0:3, 0:3]

print(region)

result = np.sum(region * kernel)

print("\nResult:", result)

[[0 0 0]
 [0 1 1]
 [0 1 1]]

Result: 2


In [4]:
output = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        region = image[i:i+3, j:j+3]
        output[i, j] = np.sum(region * kernel)

print(output)

[[ 2. -2. -2.]
 [ 2. -2. -2.]
 [ 1. -1. -1.]]
