In [1]:
import torch
import torch.nn as nn

conv = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,
    bias=False
)

print(conv)

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), bias=False)


In [2]:
print(conv.weight)
print(conv.weight.shape)

Parameter containing:
tensor([[[[ 0.2449, -0.0639,  0.2341],
          [-0.0997,  0.1974, -0.1365],
          [-0.1156,  0.1861, -0.2665]]]], requires_grad=True)
torch.Size([1, 1, 3, 3])


In [3]:
image = torch.tensor([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0],
    [0, 1, 1, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
], dtype=torch.float32)

In [4]:
x = image.unsqueeze(0).unsqueeze(0)

print(x.shape)

torch.Size([1, 1, 5, 5])


In [5]:
output = conv(x)

print(output)
print(output.shape)

tensor([[[[-0.0195,  0.1683, -0.2152],
          [ 0.2311,  0.2788,  0.1452],
          [ 0.1702,  0.1810,  0.2449]]]], grad_fn=<ConvolutionBackward0>)
torch.Size([1, 1, 3, 3])


In [6]:
print(conv.weight[0, 0])

tensor([[ 0.2449, -0.0639,  0.2341],
        [-0.0997,  0.1974, -0.1365],
        [-0.1156,  0.1861, -0.2665]], grad_fn=<SelectBackward0>)


In [7]:
conv = nn.Conv2d(
    in_channels=1,
    out_channels=3,
    kernel_size=3,
    bias=False
)

print(conv.weight.shape)

torch.Size([3, 1, 3, 3])
